### ISSUE TITLE
`which -s` is only BSD option

### ISSUE THREAD

**Issue by kyxap1** [bellthoven/bangsh#23]
# make test
bang test
Usage: /usr/bin/which [-a] args
.Usage: /usr/bin/which [-a] args
............................
real    0m4.376s
user    0m0.498s
sys     0m5.103s

Tests (Passed: 29 / Failed: 0)

**Comment by bellthoven** [comment]
This bug is fixed on master, although I am still investigating the linux-related problem. Thanks!
